version: "3.7"

services:

  mysql:
    image: mysql:5.7
    hostname: mysql
    container_name: mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: datajob
      MYSQL_ROOT_PASSWORD:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - ./scripts/create-table.sql:/docker-entrypoint-initdb.d/create-table.sql